/* Read-only project snapshot; notes and interface preferences remain in this browser. */
(() => {
  const data=window.RC_DATA||{companies:[]};
  const choices=[['workspace','Combined workspace'],['constellation','01 · Constellation'],['board','02 · Investigation board'],['desk','03 · Reading desk'],['storyline','04 · Storyline'],['matrix','05 · Signal matrix']];
  const params=new URLSearchParams(location.search);
  const first=data.companies.find(c=>c.id===(window.RC_WORKSPACE?.defaultCompany||'R01'))||data.companies[0];
  const state={companyId:params.get('company')||first?.id,eventId:params.get('event')||'',query:''};
  let render=()=>{},design='constellation',lastFocus=null;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label=value=>String(value||'unassessed').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const date=value=>{if(!value)return 'Date not recorded';const d=new Date(String(value).slice(0,10)+'T12:00:00');return Number.isNaN(d.valueOf())?String(value):new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)};
  const badge=value=>`<span class="rc-badge ${esc(String(value||'unassessed').toLowerCase().replace(/[^a-z_]/g,'_'))}">${esc(label(value))}</span>`;
  const company=()=>data.companies.find(c=>c.id===state.companyId)||first;
  const event=()=>company()?.events.find(e=>e.id===state.eventId)||company()?.events.at(-1);
  function normalize(){const c=company();if(!c)return;state.companyId=c.id;if(!c.events.some(e=>e.id===state.eventId))state.eventId=c.events.at(-1)?.id||''}
  function rerender(){normalize();render();const query=new URLSearchParams({company:state.companyId||'',event:state.eventId});history.replaceState(null,'',location.pathname+'?'+query)}
  function setEvent(id){document.dispatchEvent(new CustomEvent('rc:event-select',{detail:{id}}));state.eventId=id;rerender()}
  function setCompany(id){state.companyId=id;state.eventId='';state.query='';rerender()}
  function toolbar(id){const c=company();if(!c)return '<div class="rc-empty">No company snapshot is available. Run build_data.py to prepare it.</div>';return `<header class="rc-toolbar"><a class="rc-brand" href="index.html"><span class="rc-brand-mark">r</span>RealityCheck</a><label class="rc-company-field"><span>Company workspace</span><select aria-label="Company workspace" data-company>${data.companies.map(x=>`<option value="${esc(x.id)}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label class="rc-global-search"><span class="rc-search-symbol" aria-hidden="true">⌕</span><input type="search" aria-label="Search this company" data-query placeholder="Search reports, assumptions, evidence…" value="${esc(state.query)}"></label><label class="rc-design-field"><span>Dashboard design</span><select aria-label="Dashboard design" data-design>${choices.map(([key,name])=>`<option value="${key}" ${id===key?'selected':''}>${name}</option>`).join('')}</select></label><button class="rc-tool-button" data-export>Export snapshot ↓</button></header><div class="rc-provenance"><span><span class="rc-snapshot-dot"></span>${esc(c.id==='B01'?'Synthetic company scenario · Recorded model findings':'Public SEC filings · Reconstructed assumptions · Recorded model findings')} <button class="rc-provenance-more" data-provenance>About these records ↗</button></span><span>History through ${esc(date(c.asOf))} · Recorded analysis</span></div>`}
  function toast(text){document.querySelector('.rc-toast')?.remove();const el=document.createElement('div');el.className='rc-toast';el.role='status';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),3500)}
  function download(name,text,type='application/json'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function exportView(){download(`realitycheck-${company().id.toLowerCase()}-${design}.json`,JSON.stringify({company:company(),selectedEvent:state.eventId,source:'Recorded project snapshot',exportedAt:new Date().toISOString()},null,2));toast('Company snapshot exported')}
  function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
  function evidence(items=[]){if(!items.length)return '<p class="muted">No source passage was attached to this record.</p>';return items.map(item=>`<blockquote class="rc-quote">${esc(item.quote||'No quotation recorded')}<footer>${esc(item.locator||item.sourceId)} · ${item.verified?'Quote matched to supplied source':'Verification not recorded'} ${item.sourceId?`<button class="rc-source-link" data-source="${esc(item.sourceId)}">Open source ↗</button>`:''}</footer></blockquote>`).join('')}
  function notes(key){let value='';try{value=localStorage.getItem('rc-note-'+key)||''}catch{}return `<section class="rc-modal-section"><h3>Review notes</h3><textarea class="rc-notes" aria-label="Review notes" data-note-key="${esc(key)}" placeholder="Add your observations for this review…">${esc(value)}</textarea><div class="rc-notes-line"><span>Saved only in this browser. Source records stay unchanged.</span><button class="rc-tool-button" data-save-note>Save note</button></div></section>`}
  function modal(title,eyebrow,content){let dialog=document.getElementById('rc-inspector');if(!dialog){dialog=document.createElement('dialog');dialog.id='rc-inspector';dialog.className='rc-modal';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>lastFocus?.focus?.())}if(!dialog.open)lastFocus=document.activeElement;dialog.innerHTML=`<div class="rc-modal-head"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div><button class="rc-close" aria-label="Close details" data-close>×</button></div><div class="rc-modal-body">${content}</div>`;if(!dialog.open)dialog.showModal();dialog.scrollTop=0}
  function showSource(id){const c=company(),s=c.sources.find(x=>x.id===id);if(!s){toast('The original source text is not available in this snapshot.');return}const related=c.assumptions.filter(a=>a.evidence.some(e=>e.sourceId===id)||c.events.some(v=>v.findings.some(f=>f.assumptionId===a.id&&f.evidence.some(q=>q.sourceId===id))));const url=safeUrl(s.url);modal(s.title,'Source library · '+c.name,`<div class="rc-modal-meta"><span>${esc(s.kind)}</span><span>${esc(date(s.date))}</span><span class="mono">${esc(s.id)}</span></div><p class="muted" style="font-size:12px;margin-top:12px">Source coverage: ${esc(s.locator||"Stored source record")}</p><div class="rc-modal-actions">${url?`<a class="rc-modal-action" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open original filing ↗</a>`:''}<button class="rc-modal-action" data-download-source="${esc(s.id)}">Download source text</button></div><article class="rc-source-text">${esc(s.text||'Source text is not present in this snapshot.')}</article><section class="rc-modal-section"><h3>Connected assumptions</h3>${related.map(a=>`<div class="rc-detail-row"><button class="rc-source-link" data-assumption="${esc(a.id)}">${esc(a.title)}</button> ${badge(a.status)}</div>`).join('')||'<p class="muted">No explicit assumption connection is recorded for this source.</p>'}</section>${notes(c.id+':'+id)}`)}
  function showAssumption(id){const c=company(),a=c.assumptions.find(x=>x.id===id);if(!a){toast('Assumption is not available in this snapshot.');return}const rows=c.events.flatMap(e=>e.findings.filter(f=>f.assumptionId===id).map(f=>({e,f})));modal(a.title,'Assumption · '+a.id,`${badge(a.status)}<p style="margin:16px 0;font-size:17px;line-height:1.7">${esc(a.claim)}</p><p class="muted" style="font-size:12px">Baseline: ${esc(a.basis)}. Status reflects the latest recorded assessment, where available.</p><section class="rc-modal-section"><h3>Original evidence</h3>${evidence(a.evidence)}</section><section class="rc-modal-section"><h3>Assessment history</h3>${rows.map(({e,f})=>`<div class="rc-detail-row"><span class="eyebrow">${esc(date(e.date))}</span><strong><button class="rc-source-link" data-inspect-event="${esc(e.id)}">${esc(e.title)}</button></strong>${badge(f.status)}<p>${esc(f.rationale)}</p>${evidence(f.evidence)}</div>`).join('')||'<p class="muted">No recorded event assessment targets this assumption.</p>'}</section><section class="rc-modal-section"><h3>Linked contractual provisions · reference baseline</h3><p class="muted" style="font-size:12px">Dated amendments are recorded separately in package history.</p>${a.covenantIds.map(id=>{const v=c.covenants.find(x=>x.id===id);return `<div class="rc-detail-row"><strong>${esc(id)} · ${esc(v?.title||'Contractual provision')}</strong><p>${esc(v?.text||'Full clause text is not included in this snapshot.')}</p></div>`}).join('')||'<p class="muted">No explicit provision link recorded.</p>'}</section>${notes(c.id+':'+id)}`)}
  function showEvent(id){const c=company(),e=c.events.find(x=>x.id===id);if(!e){toast('Event is not available in this snapshot.');return}modal(e.title,'Recorded investigation · '+date(e.date),`<p style="font-size:16px;line-height:1.75">${esc(e.summary)}</p><div class="rc-modal-meta"><span>Model: ${esc(e.model||c.model||'Not recorded')}</span><span>${esc(label(e.analysisStatus))}</span><span>${esc(e.id)}</span></div><section class="rc-modal-section"><h3>Source packet</h3>${e.sourceIds.map(id=>{const s=c.sources.find(x=>x.id===id);return `<div class="rc-detail-row"><button class="rc-source-link" data-source="${esc(id)}">${esc(s?.title||id)} ↗</button></div>`}).join('')||'<p class="muted">No source references recorded.</p>'}</section><section class="rc-modal-section"><h3>Recorded findings</h3>${e.findings.map(f=>{const a=c.assumptions.find(x=>x.id===f.assumptionId);return `<div class="rc-detail-row"><strong>${a?`<button class="rc-source-link" data-assumption="${esc(a.id)}">${esc(a.title)}</button>`:esc(f.assumptionId||'Covenant assessment')}</strong>${badge(f.status)}<p style="margin-top:8px"><b>Credit implication:</b> ${esc(f.implication||"Not recorded")}</p><p style="margin-top:10px">${esc(f.rationale)}</p>${f.action?`<p><b>Suggested action:</b> ${esc(label(f.action))}</p>`:''}${evidence(f.evidence)}</div>`}).join('')||'<p class="muted">No validated assumption attributions are present in this recorded result.</p>'}</section>${notes(c.id+':'+id)}`)}
  function init(id,fn){design=id;render=fn;normalize();render();document.addEventListener('change',e=>{if(e.target.matches('[data-company]'))setCompany(e.target.value);if(e.target.matches('[data-design]'))location.href=e.target.value+'.html?'+new URLSearchParams({company:state.companyId,event:state.eventId})});let timer;document.addEventListener('input',e=>{if(!e.target.matches('[data-query]'))return;const position=e.target.selectionStart;state.query=e.target.value;clearTimeout(timer);timer=setTimeout(()=>{render();const input=document.querySelector('[data-query]');input?.focus();try{input?.setSelectionRange(position,position)}catch{}},170)});document.addEventListener('click',e=>{const b=e.target.closest('button,[data-source],[data-assumption],[data-event]');if(!b)return;if(b.hasAttribute('data-source'))showSource(b.dataset.source);else if(b.hasAttribute('data-assumption'))showAssumption(b.dataset.assumption);else if(b.hasAttribute('data-event'))setEvent(b.dataset.event);else if(b.hasAttribute('data-inspect-event'))showEvent(b.dataset.inspectEvent);else if(b.hasAttribute('data-export'))exportView();else if(b.hasAttribute('data-provenance'))modal('About these records',company().name,`<p style="line-height:1.9">${esc(company().provenance)}</p><section class="rc-modal-section"><h3>Company context and reviewer notes</h3><p style="white-space:pre-line;line-height:1.9">${esc(company().summary)}</p></section><section class="rc-modal-section"><h3>Recorded model</h3><p>${esc(company().model)}</p><p style="margin-top:12px">Documents retain their source and dates. These screens display saved historical analyses; they do not run a new investigation or change contractual terms.</p></section>`);else if(b.hasAttribute('data-close'))document.getElementById('rc-inspector').close();else if(b.hasAttribute('data-download-source')){const s=company().sources.find(x=>x.id===b.dataset.downloadSource);if(s)download(s.id.replace(/[^a-zA-Z0-9_-]/g,'_')+'.txt',s.text,'text/plain')}else if(b.hasAttribute('data-save-note')){const field=document.querySelector('[data-note-key]');try{localStorage.setItem('rc-note-'+field.dataset.noteKey,field.value);toast('Review note saved in this browser')}catch{toast('Browser storage is unavailable. Copy the note before closing.')}}})}
  window.RC={data,state,company,event,esc,date,badge,label,toolbar,init,showSource,showAssumption,showEvent,setEvent,setCompany,exportView,evidence,toast,modal,safeUrl};
})();
