(() => {
  'use strict';
  const ui={kind:'all',year:'all',order:'newest',detail:'assessments',versionId:'',limit:6,companyId:''};
  const list=v=>Array.isArray(v)?v:[];
  const text=v=>v==null?'':typeof v==='object'?JSON.stringify(v):String(v);
  const e=v=>RC.esc(text(v));
  const short=(v,max=200)=>text(v).length>max?text(v).slice(0,max).trim()+'…':text(v);
  const dateParts=date=>{const d=new Date(text(date).slice(0,10)+'T12:00:00');return Number.isNaN(d.valueOf())?{day:'—',month:'UNDATED',year:''}:{day:String(d.getDate()).padStart(2,'0'),month:d.toLocaleDateString('en-US',{month:'short'}).toUpperCase(),year:String(d.getFullYear())};};
  const icon=name=>`<svg class="s-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({timeline:'<path d="M6 3v18M11 5h9M11 12h6M11 19h9"/><circle cx="6" cy="5" r="2" fill="currentColor" stroke="none"/><circle cx="6" cy="12" r="2" fill="currentColor" stroke="none"/><circle cx="6" cy="19" r="2" fill="currentColor" stroke="none"/>',report:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/>',package:'<path d="m12 3 9 5-9 5-9-5 9-5zM3 8v9l9 5 9-5V8M12 13v9M7 5l10 6"/>',arrow:'<path d="M4 12h16m-5-5 5 5-5 5"/>',prev:'<path d="m14 6-6 6 6 6"/>',next:'<path d="m10 6 6 6-6 6"/>',replay:'<path d="M4 4v6h6M4 10a8 8 0 1 1 0 5"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>',sort:'<path d="M8 3v18m-4-4 4 4 4-4M16 21V3m-4 4 4-4 4 4"/>',source:'<path d="M4 4h7v16H4zM14 4h6v16h-6M7 8h1m9 0h1"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>'})[name]||''}</svg>`;
  function data(){
    const company=RC.company();
    if(ui.companyId!==company.id){ui.companyId=company.id;ui.kind='all';ui.year='all';ui.versionId='';ui.limit=6;}
    const events=[...list(company.events)].sort((a,b)=>text(a.date).localeCompare(text(b.date)));
    const versions=[...list(company.versions)].sort((a,b)=>text(a.date).localeCompare(text(b.date)));
    const event=RC.event()||events.at(-1)||{};
    const selectedIndex=events.findIndex(x=>x.id===event.id);
    const previous=assumptionId=>events.slice(0,Math.max(selectedIndex,0)).reverse().flatMap(ev=>list(ev.findings)).find(f=>f.assumptionId===assumptionId);
    let entries=[...events.map(v=>({...v,type:'report'})),...versions.map(v=>({...v,type:'package'}))];
    const query=text(RC.state.query).toLowerCase();
    entries=entries.filter(v=>(ui.kind==='all'||ui.kind===v.type)&&(ui.year==='all'||text(v.date).slice(0,4)===ui.year)&&(!query||text([v.title,v.summary,v.id,...list(v.findings).map(f=>f.rationale)]).toLowerCase().includes(query)));
    entries.sort((a,b)=>ui.order==='newest'?text(b.date).localeCompare(text(a.date)):text(a.date).localeCompare(text(b.date)));
    return {company,events,versions,event,selectedIndex,previous,entries};
  }
  function nav({company,events,versions,event}){
    const years=[...new Set([...events,...versions].map(v=>text(v.date).slice(0,4)).filter(Boolean))].sort().reverse();
    return `<aside class="s-nav"><h2 class="s-nav-label">Workspace</h2>${[['all','timeline','Full timeline',events.length+versions.length],['report','report','Reports',events.length],['package','package','Package history',versions.length]].map(([kind,ic,label,count])=>`<button class="s-nav-link ${ui.kind===kind?'active':''}" data-s-kind="${kind}">${icon(ic)}${label}<small>${count}</small></button>`).join('')}<button class="s-nav-link" data-s-library="sources">${icon('source')}Source library<small>${list(company.sources).length}</small></button><hr class="s-nav-divider"><h3 class="s-nav-label">Jump to year</h3><button class="s-year-button ${ui.year==='all'?'active':''}" data-s-year="all">All years<span>${events.length+versions.length}</span></button>${years.map(year=>`<button class="s-year-button ${ui.year===year?'active':''}" data-s-year="${e(year)}">${e(year)}<span>${[...events,...versions].filter(v=>text(v.date).startsWith(year)).length}</span></button>`).join('')}<hr class="s-nav-divider"><h3 class="s-nav-label">Reporting moments</h3><div class="s-jump-list">${[...events].reverse().map(ev=>`<button class="s-jump ${ev.id===event.id?'active':''}" data-s-event="${e(ev.id)}"><time>${e(RC.date(ev.date))}</time>${e(short(ev.title,64))}</button>`).join('')}</div><hr class="s-nav-divider"><p class="s-nav-context"><strong>${e(company.id)} · ${e(company.name)}</strong>${e(company.sector || 'Credit monitoring')}<br>${list(company.assumptions).length} underwriting assumptions<br>History through ${e(RC.date(company.asOf))}</p></aside>`;
  }
  function replay({events,event,selectedIndex}){
    return `<section class="s-replay" aria-label="Replay saved reporting history"><div class="s-replay-head"><strong>${icon('replay')}Replay recorded history</strong><span>Moment ${selectedIndex+1} of ${events.length}</span><div class="s-replay-controls"><button data-s-step="-1" ${selectedIndex<=0?'disabled':''} aria-label="Previous reporting moment">${icon('prev')}</button><button data-s-step="1" ${selectedIndex>=events.length-1?'disabled':''} aria-label="Next reporting moment">${icon('next')}</button></div></div><div class="s-replay-track">${events.map((ev,i)=>`<button data-s-event="${e(ev.id)}" class="${i<selectedIndex?'past':i===selectedIndex?'current':''}" aria-label="${e(RC.date(ev.date))}: ${e(ev.title)}" title="${e(RC.date(ev.date))} · ${e(ev.title)}"></button>`).join('')}</div><div class="s-replay-dates"><span>${e(RC.date(events[0]?.date))}</span><span>${e(RC.date(event.date))} selected</span><span>${e(RC.date(events.at(-1)?.date))}</span></div></section>`;
  }
  function entry(v,{company,event}){
    const d=dateParts(v.date),isPackage=v.type==='package',selected=isPackage?ui.versionId===v.id:!ui.versionId&&v.id===event.id;
    const findings=list(v.findings);
    const firstFinding=findings[0];
    const assumption=list(company.assumptions).find(a=>a.id===firstFinding?.assumptionId);
    return `<article class="s-entry ${isPackage?'s-version-entry':''} ${selected?'selected':''}" id="s-entry-${e(v.id)}"><div class="s-date"><strong>${e(d.day)}</strong>${e(d.month)}<br>${e(d.year)}</div><div class="s-entry-body"><div class="s-report-top"><span class="s-report-kind">${icon(isPackage?'package':'report')}${isPackage?'Credit package':'Reporting moment'}</span>${isPackage?`<span class="s-version-version">v${e(v.version)}</span>`:selected?'<span class="s-selected-flag">In focus</span>':`<span class="s-selected-flag">${findings.length} recorded findings</span>`}</div><div class="s-report-inner"><button class="s-report-title" ${isPackage?`data-s-version="${e(v.id)}"`:`data-s-event="${e(v.id)}"`}>${e(v.title)}</button><div class="s-report-summary">${e(short(v.summary,isPackage?160:220))}${text(v.summary).length>220&&!isPackage?`<details><summary>Read report context & review notes</summary><p>${e(v.summary)}</p></details>`:''}</div>${!isPackage?`<div class="s-report-tags"><span class="s-tag">${icon('source')}${list(v.sourceIds).length} source ${list(v.sourceIds).length===1?'document':'documents'}</span><span class="s-tag">${icon('grid')}${new Set(findings.map(f=>f.assumptionId)).size} assessed inquiries</span></div>${firstFinding?`<div class="s-finding-preview"><div class="s-finding-name"><span>${e(assumption?.title||firstFinding.assumptionId)}</span>${RC.badge(firstFinding.status)}</div><p>${e(short(firstFinding.implication || firstFinding.rationale,180))}</p></div>`:''}`:''}</div><footer class="s-report-footer"><span>${isPackage?`${list(v.changes).length} recorded changes · ${e(v.status || 'Status not recorded')}`:e(v.id)+' · Recorded analysis'}</span><button class="s-link" ${isPackage?`data-s-version="${e(v.id)}"`:`data-s-event="${e(v.id)}"`}>${isPackage?'Inspect package':'Inspect moment'}${icon('arrow')}</button></footer></div></article>`;
  }
  function inspector(c){
    const {company,event,previous,versions}=c;
    const version=versions.find(v=>v.id===ui.versionId);
    if(version){
      return `<aside class="s-inspector"><div class="s-inspector-head"><div class="s-inspector-top">Package inspector ${icon('package')}</div><div class="s-inspector-date">${e(RC.date(version.date))} · v${e(version.version)}</div><h2>${e(version.title)}</h2><span class="s-version-version">${e(version.status || 'Status not recorded')}</span></div><div class="s-inspector-content"><h3 class="s-inspector-label">Version summary</h3><p class="s-nav-context" style="font-size:12px">${e(version.summary)}</p><h3 class="s-inspector-label">Recorded package changes</h3>${list(version.changes).length?`<ul class="s-version-list">${version.changes.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`:'<div class="s-empty">No individual change entries were attached to this package version.</div>'}<h3 class="s-inspector-label">Original package provisions</h3><p class="s-nav-context">${list(company.covenants).length} original and added provision records are available. Dated amendments may change their terms.</p><div class="s-inspector-actions"><button class="s-button" data-s-library="covenants">Inspect provisions ${icon('arrow')}</button></div></div><div class="s-inspector-actions"><button class="s-button" data-s-back>Return to report ${icon('arrow')}</button></div><div class="s-record-note">Package version information is taken from the saved repository records.</div></aside>`;
    }
    const findings=list(event.findings);
    let body='';
    if(ui.detail==='sources'){
      body=`<h3 class="s-inspector-label">Report source packet</h3>${list(event.sourceIds).map(id=>{const s=list(company.sources).find(x=>x.id===id);return `<article class="s-source-item"><button class="s-link" data-source="${e(id)}">${icon('report')}${e(s?.title||id)}</button><p>${e(s?.kind||'Source record')}<br>${e(RC.date(s?.date))}<br>${e(s?.id||id)}</p></article>`}).join('')||'<div class="s-empty">No source references are attached to this moment.</div>'}${findings.flatMap(f=>list(f.evidence)).slice(0,3).map(item=>`<div class="s-passage"><blockquote>“${e(item.quote)}”</blockquote><footer>${e(item.locator||'Locator not recorded')} · ${item.verified?'Verified quotation':'Verification not recorded'}</footer>${item.sourceId?`<button class="s-link" style="margin-top:10px" data-source="${e(item.sourceId)}">Inspect source ${icon('arrow')}</button>`:''}</div>`).join('')}`;
    }else if(ui.detail==='context'){
      const preceding=versions.filter(v=>text(v.date)<=text(event.date)).at(-1);
      body=`<h3 class="s-inspector-label">Report context & review notes</h3><p class="s-nav-context" style="font-size:11px;white-space:pre-line">${e(event.summary||'No report summary recorded.')}</p>${preceding?`<div class="s-package-mini"><h3>Package v${e(preceding.version)} · ${e(preceding.title)}</h3><p>Latest package dated on or before this report: ${e(RC.date(preceding.date))}.</p><button class="s-link" data-s-version="${e(preceding.id)}">Inspect package ${icon('arrow')}</button></div>`:''}`;
    }else{
      body=`<h3 class="s-inspector-label">Assessment transitions</h3>${findings.length?findings.map(f=>{
        const a=list(company.assumptions).find(x=>x.id===f.assumptionId),prior=previous(f.assumptionId);
        return `<article class="s-transition"><h3 class="s-transition-title">${e(a?.title||f.assumptionId)}</h3><div class="s-transition-status"><span class="s-previous">${e(prior?RC.label(prior.status):'No prior assessment')}</span>${icon('arrow')}${RC.badge(f.status)}</div><p>${e(short(f.rationale,260))}</p>${text(f.rationale).length>260?`<details><summary>Full rationale & review notes</summary><p>${e(f.rationale)}</p></details>`:''}<div class="s-transition-footer"><button class="s-link" data-assumption="${e(f.assumptionId)}">Assumption history ${icon('arrow')}</button><span>${list(f.evidence).length} evidence links</span></div></article>`;
      }).join(''):'<div class="s-empty">No validated assumption findings are attached to this recorded moment.</div>'}<p class="s-nav-context">Transitions compare the previous saved finding for each assumption with the selected report. Risk direction and assumption status are separate fields.</p>`;
    }
    return `<aside class="s-inspector"><div class="s-inspector-head"><div class="s-inspector-top">Moment inspector ${icon('timeline')}</div><div class="s-inspector-date">${e(RC.date(event.date))} · ${e(event.id)}</div><h2>${e(event.title||'No reporting moment')}</h2><div class="s-inspector-selected">Selected reporting moment</div></div><nav class="s-inspector-tabs" aria-label="Moment detail">${[['assessments','Assessments'],['sources','Sources'],['context','Context']].map(([id,label])=>`<button class="${ui.detail===id?'active':''}" data-s-detail="${id}">${label}</button>`).join('')}</nav><div class="s-inspector-content">${body}</div><div class="s-inspector-actions"><button class="s-button" data-inspect-event="${e(event.id)}">Full report record ${icon('arrow')}</button></div><div class="s-record-note"><div class="s-model"><span class="s-model-dot"></span><span>${e(event.analysisStatus||'Recorded analysis')}</span></div><div style="margin-top:8px">Recorded model: ${e(event.model||company.model||'Not recorded')}</div></div></aside>`;
  }
  function render(){
    const c=data(),{company,events,versions,entries}=c;
    document.getElementById('app').innerHTML=`${RC.toolbar('storyline')}<div class="s-shell"><header class="s-header"><div class="s-eyebrow">Company intelligence <span>/</span> ${e(company.id)} <span>/</span> Storyline</div><div class="s-header-main"><div><h1>Every report. The whole story.</h1><p>${e(company.name)} · Follow the evidence, the assessments, and the changing credit package.</p></div><div class="s-header-actions"><button class="s-button" data-export>${icon('download')}Export timeline</button><button class="s-button primary" data-s-replay>${icon('replay')}Replay from the start</button></div></div><div class="s-header-foot"><nav class="s-top-tabs" aria-label="Timeline views">${[['all','Timeline',events.length+versions.length],['report','Reports',events.length],['package','Package versions',versions.length]].map(([kind,label,count])=>`<button class="${ui.kind===kind?'active':''}" data-s-kind="${kind}">${label}<span>${count}</span></button>`).join('')}</nav><span class="s-header-note">Dated repository records · ${list(company.sources).length} sources</span></div></header><div class="s-workspace">${nav(c)}<main class="s-main">${replay(c)}<div class="s-list-tools"><h2>${ui.kind==='package'?'Credit package history':ui.kind==='report'?'Reporting history':'The company timeline'}${ui.year!=='all'?` · ${e(ui.year)}`:''}</h2><button data-s-sort>${icon('sort')}${ui.order==='newest'?'Newest first':'Oldest first'}</button></div>${RC.state.query?`<p class="s-query-note">${entries.length} matching records for “${e(RC.state.query)}”</p>`:''}${entries.length?entries.slice(0,ui.limit).map(v=>entry(v,c)).join(''):'<div class="s-empty">No records match this view. Choose a different year, change the record type, or clear the company search.</div>'}${entries.length>ui.limit?`<div class="s-pagination"><button class="s-button" data-s-more>Show ${Math.min(6,entries.length-ui.limit)} more records ${icon('arrow')}</button></div>`:''}<footer class="s-bottom"><span>${Math.min(ui.limit,entries.length)} of ${entries.length} timeline records in view</span><span>Saved history · Source inspection available</span></footer></main>${inspector(c)}</div></div>`;
  }
  document.addEventListener('click',ev=>{
    const b=ev.target.closest('[data-s-kind],[data-s-year],[data-s-sort],[data-s-detail],[data-s-step],[data-s-event],[data-s-version],[data-s-replay],[data-s-more],[data-s-back],[data-s-library]');
    if(!b)return;
    if(b.hasAttribute('data-s-event')){ui.versionId='';RC.setEvent(b.dataset.sEvent);return;}
    if(b.hasAttribute('data-s-step')){const c=data(),next=c.events[c.selectedIndex+Number(b.dataset.sStep)];if(next){ui.versionId='';RC.setEvent(next.id);}return;}
    if(b.hasAttribute('data-s-replay')){const c=data();ui.kind='all';ui.year='all';ui.order='oldest';ui.limit=6;ui.versionId='';if(c.events[0])RC.setEvent(c.events[0].id);else render();return;}
    if(b.hasAttribute('data-s-kind')){ui.kind=b.dataset.sKind;ui.limit=6;}
    if(b.hasAttribute('data-s-year')){ui.year=b.dataset.sYear;ui.limit=6;}
    if(b.hasAttribute('data-s-sort')){ui.order=ui.order==='newest'?'oldest':'newest';ui.limit=6;}
    if(b.hasAttribute('data-s-detail'))ui.detail=b.dataset.sDetail;
    if(b.hasAttribute('data-s-version'))ui.versionId=b.dataset.sVersion;
    if(b.hasAttribute('data-s-back'))ui.versionId='';
    if(b.hasAttribute('data-s-more'))ui.limit+=6;
    if(b.hasAttribute('data-s-library')){
      const c=RC.company();
      if(b.dataset.sLibrary==='sources')RC.modal('Source library',c.name,list(c.sources).map(s=>`<article class="rc-detail-row"><button class="rc-source-link" data-source="${e(s.id)}">${e(s.title)}</button><p>${e(s.kind)} · ${e(RC.date(s.date))}</p></article>`).join('')||'<p>No sources recorded.</p>');
      else RC.modal('Original and added provisions',c.name,'<p class="muted">Dated amendments may change these terms. Inspect package versions for the recorded changes.</p>'+ list(c.covenants).map(v=>`<article class="rc-detail-row"><strong>${e(v.id)} · ${e(v.title)}</strong><p>${e(v.text)}</p></article>`).join('')||'<p>No contractual provision records.</p>');
      return;
    }
    render();
  });
  RC.init('storyline',render);
})();
